[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install --include=optional"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run preview -- --host 0.0.0.0 --port 3000"
